---
title: "US EHE/ECE Data Integration and Visualization"
author: "Pedram Fard"
format: html
editor: visual
---

```{r setup, include=FALSE}
library(readr)
library(viridis)
library(tidyverse)
library(sf)
library(leaflet)
```

## Loading the base spatial data set including Counties and States boundaries

```{r}
source_dir <- "./data/"

states_file_path <- file.path(source_dir,
                              "us49_states_geo_tigris.rds")
states_geo <- readRDS(states_file_path)[[1]]

counties_file_path <- file.path(source_dir,
                                "us49_counties_geo_tigris.rds")
counties_geo <- readRDS(counties_file_path)[[1]]

plot(counties_geo[1])
```

## Loading the aggregate extreme events data set

```{r load the aggreagte events summaries at State level}
events_catalog_file_path <- file.path(source_dir,
                                      "States_events_by_type_sf_2008_2022.rds") 

events_catalog_sf <- readRDS(events_catalog_file_path)[[1]] %>% 
  dplyr::filter(event_type == "Extreme Heat Event")

glimpse(events_catalog_sf)
```

## Example of merging States boundaries with summarized EHE data

```{r }
state_boundaris_ehe_catalog <- merge(states_geo,
          events_catalog_sf %>% st_drop_geometry(),
          by.x="GEOID",
          by.y="GEOID",
          all.x = TRUE,
          all.y = TRUE,
          suffix = c("","_sp")) %>% st_as_sf()  %>% st_transform(crs = 4326)

glimpse(state_boundaris_ehe_catalog)
```

## Interactive mapping the summarized EHE data merged with the States boundaries

```{r}
# define the color palette
pal <- colorNumeric(palette = magma(256, direction = -1), domain = state_boundaris_ehe_catalog$total_event_days)

total_ehe_interactive_plot <- leaflet(state_boundaris_ehe_catalog) %>%
  addProviderTiles(providers$OpenStreetMap) %>% 
  addPolygons(fillColor = ~pal(total_event_days),
              weight = 1,
      opacity = 1,
      color = "#888",
      dashArray = "3",
      fillOpacity = 0.7,
      highlightOptions = highlightOptions(
        weight = 3,
        color = "#555",
        dashArray = "",
        fillOpacity = 0.8,
        bringToFront = TRUE),
      label = ~as.character(total_event_days)) %>% 
  addControl(
    html = "<strong>Total Number of EHE Days (2008-2022)</strong>",
    position = "bottomleft",
    className = "map-title"
)

total_ehe_interactive_plot
```
