---
title: "Extreme Heat and Cold Events (EHE/ECE) Exploration"
format: html
---

## Introduction

This is a Quarto document to read and explore the catalog of the Extreme Heat and Cold Events (EHE/ECE) within contiguous U.S.

## Load the events data set
```{r}
library(tidyverse)
library(sf)

# set the path pointing to the RDS files storing event catalogs
events_catalog_file_path <- file.path("~/US_EHE_ECE/tracts/",
                                         # aggregate summary by event type for the entire study period
                                         "Tracts_events_by_type_sf.rds")  

                                         # aggregate annual summary
                                         #"Tracts_events_by_year_sf.rds"

                                         # aggregate annual summary by event type
                                         #"Tracts_events_by_type_by_year_sf.rds"

                                         # disaggregated daily catalog of the extreme events 
                                         #"contiguous_us_tracts_events_catalog.rds"

# read the spatial layer of census unit in sf class
events_catalog_sf <- readRDS(events_catalog_file_path)
```

## Visualize frequency and geography of impacted areas
```{r}
pal <- c(
                                #"white",  
                                # "darkgreen", 
                                "lightgreen", 
                                "khaki", 
                                "orange2", 
                                "coral2",
                                "red4")

frequency_map <- ggplot() +
  geom_sf(data = events_catalog_sf,
          aes(fill = total_event_days),
          lwd = .1) + 
  #scale_fill_viridis_c(alpha = 1, direction = -1) +
  scale_fill_gradientn(colors = pal, 
                       na.value = NA) + 
    labs(fill = "Total Number of ECE/EHE Days") +
    labs(title = "Extent of the Extreme Event Impacts within Contiguous U.S") +
    facet_grid("event_type") + # ceate separate maps for the cold and heat events
  theme_bw()

frequency_map
```


## Visualize the frequency for a specific state
```{r}
geog <- c("California")

events_catalog_sf_stat <- events_catalog_sf %>% filter(STATE_NAME %in% geog) 
  
  
frequency_map_state <- ggplot() +
  geom_sf(data = events_catalog_sf_stat,
          aes(fill = total_event_days),
          lwd = .1) + 
  #scale_fill_viridis_c(alpha = 1, direction = -1) +
  scale_fill_gradientn(colors = pal, 
                       na.value = NA) + 
    labs(fill = "Total Number of ECE/EHE Days") +
    labs(title = paste0("Extent of the Extreme Event Impacts in ", geog)) +
    facet_grid("event_type") + # ceate separate maps for the cold and heat events
  theme_bw()

frequency_map_state
```
