---
title: "GridEx Extreme Events Identification"
subtitle: "Exploring the curated NOAA dataset"
author: "Pedram Fard"

format: html
editor: visual
---

## Example of IDW interpolation using the curated NOAA sensors dataset

```{r setup, include=FALSE}
## install.packages(c("sf", "terra", "tidyverse"))

## install.packages(c("leaflet"))

library(sf)
library(tidyverse)
library(data.table)
library(tibble)

#library(readr)
#library(viridis)
#library(terra)

workshop_dataset <- "../Data"
# Check out the data folders for today workshop
list.files(workshop_dataset, full.names = TRUE)

data_dir <- "../Data/NOAA_sensors_dataset"
list.files(data_dir, "rds")
```

```{r}
library("raster")

#blank_grid_10km <- terra::rast(file.path(data_dir, "blank_grid_stars_clipped_10000.tif"))
#blank_grid_10km <- st_read(file.path(data_dir, "blank_grid_stars_coded_10000.gpkg"))
blank_grid_10km <- readRDS(file.path(data_dir, "blank_grid_stars_10000.rds"))

glimpse(blank_grid_10km)
#blank_grid <- st_crop(blank_grid,
#                       states_geo)
#plot(blank_grid)
#plot(masking_layer, add = T, col = "orange")


noaa_stations <- st_read(file.path(data_dir, "NOAA_C16_S900_noaa_stations_geo_CRS5070.gpkg"))
class(noaa_stations)

blank_grid_SP = as(blank_grid_10km, "Spatial")

st_crs(blank_grid_10km)
st_crs(noaa_stations)$epsg
st_crs(blank_grid_SP)
# calculate the exact number of cells in the idw
idw_blank <- gstat::idw(z ~ 1,
                        noaa_stations,
                        newdata = blank_grid_SP,
                        nmax = 6,
                        idp = 2)

idw_blank_raster <- terra::rast(idw_blank)[[1]]
crs(idw_blank_raster) <- paste0("epsg:", spatial_projection)
idw_blank_raster <- crop(idw_blank_raster[[1]], raster::extent(masking_layer))
idw_blank_raster[(idw_blank_raster < 1)] <- NA 

total_grids <- length(idw_blank_raster[!is.na(idw_blank_raster)])

# list the files
list.files(GridEX_C15_T902, full.names = TRUE, pattern = "gpkg")



noaa_daily_imputed <- readRDS(file.path(data_dir, "C16_S909_T001_noaa_daily_imputed_tb.rds"))
class(noaa_daily_imputed)

C15_S909_T002_noaa_ehe_ece_days_tb

dim(noaa_stations)
ls(noaa_stations)

View(noaa_stations)

hist(noaa_stations$elev_m)
plot(noaa_stations["elev_m"])
```

Here we get started with retrieving the daily national dataset of EHE/ECE covering the continental United States over the past 15 years

```{r}
hist(noaa_stations$elev_m)


gc()
map_polygons <- leaflet() %>%
addProviderTiles(providers$OpenStreetMap, group = "OSM (default)") %>% # 
  
  setView(lng = -71.3824, lat = 42.4072, zoom = 7) %>% # Set the view to Massachusetts
addLayersControl(
    baseGroups = c("OSM (default)"),
    overlayGroups = c("Zip3", "Stations Voronoi", "NOAA Stations"),
    options = layersControlOptions(collapsed = FALSE)
) %>%
addPolygons(data = zctas_geo_3digits, color = "blue", fill = FALSE, group = "Zip3") %>% # Add the first layer
#addLabelOnlyMarkers(data = zctas_geo_3digits_voronoi_cl, label = ~zip3, labelOptions = labelOptions(noHide = TRUE, direction = 'center')) %>% 
addPolygons(data = stations_geo_voronoi_cl, color = "red4", fill = FALSE,
            label = ~paste0(station_id), group = "Stations Voronoi") %>% 
addCircleMarkers(data = stations_geo, radius = 3, color = "red4", 
                 label = ~paste0(station_id, "\n", state), group = "NOAA Stations")

map_polygons
```

## Base layers

```{r}
impacts_source_dir <- "/n/scratch/users/p/pef004/us_climate_data_s/06_US_ehe_ece_65_by_station_GridEX_March_5070S2_500_6_2/GridEX_S123_T002_daily_vector_dataset_GPKG_500"

list.files(impacts_source_dir, "201_")

tracts_Y2022 <- st_read(file.path(grids_source_dir, "Y2022_S201_T002_impacted_area_variables_intensity_Tracts_wideformat_CRS4269_CA.gpkg"))

dim(tracts_Y2022)

glimpse(tracts_Y2022)
#plot(Y2022_dataset)
```

```{r}
# library(ggplot2)
# library(raster)
# library(terra)
# library(ncdf4)

girdex_yearly_dir <- "../Data/GridEX_C15_S526_T902_cumulative_raster_dataset"
list.files(girdex_yearly_dir)

ehce_stack_file <- file.path(girdex_yearly_dir, "T002_C15_S426_ehce_unified_grids_500_stack_yearly.tif")
ehce_stack_terra <- rast(ehce_stack_file)
class(ehce_stack_terra)
dim(ehce_stack_terra)
str(ehce_stack_terra)

plot(ehce_stack_terra["2022"])

      number_of_layers <- nlyr(ehce_stack_terra)
      crs <- st_crs(ehce_stack_terra)$input
      epsg <- st_crs(ehce_stack_terra)$epsg
      cell_size <- res(ehce_stack_terra)
      num_cells <- ncell(ehce_stack_terra)
      min_value <- minmax(raster_layer)[1,1]
      max_value <- minmax(raster_layer)[2,1]
```

```{r}
daily_grids_dir <- "../Data/GridEX_C15_S526_T002_daily_raster_dataset"
list.files(daily_grids_dir, full.names = TRUE)

ehce_daily_file <- file.path(daily_grids_dir, "D2022-01-02_S526_T002_idw_ehce_grid.tif")

ehce_stack_file <- file.path(daily_grids_dir, "T002_C15_S426_ehce_unified_grids_500_stack_yearly.tif")
ehce_stack_terra <- rast(ehce_stack_file)

class(ehce_stack_terra)
dim(ehce_stack_terra)
nlyr(ehce_stack_terra)

plot(ehce_stack_terra)

plot(ehce_stack_terra[[1]])
plot(noaa_stations[2], pch = 16, col = "black", add = T)
```

```{r}
ehce_stack_rasterlayer <- raster::brick(ehce_stack_file)
class(ehce_stack_rasterlayer)
dim(ehce_stack_rasterlayer)
str(ehce_stack_rasterlayer)

plot(ehce_stack_rasterlayer)
```

```{r}
ehce_cml_file <- file.path(girdex_yearly_dir, "T102_C15_S426_ehce_unified_grids_500_cumulative_yearly.tif")
ehce_cml_terra <- rast(ehce_cml_file)
class(ehce_cml_terra)
dim(ehce_cml_terra)
str(ehce_cml_terra)

plot(ehce_cml_terra)
```

```{r}
ehce_cml_raster <- raster(ehce_cml_file)
class(ehce_cml_raster)
dim(ehce_cml_raster)
str(ehce_cml_raster)

plot(ehce_cml_raster)
```

```         
```
